### ISSUE TITLE
Where are the CDK scripts that make up the infrastructure?

### ISSUE THREAD

**Issue by deleugpn** [aws-samples/aws-cdk-changelogs-demo#1]
I looked over the source code and saw the CDK.json which seem a simple configuration and the package.json which requires some CDK objects.
However I can't seem to find where are the CDK files that make up this application on an AWS account from scratch.
I'm looking forward to learning more about CDK and how to avoid a lot of repetitive template code by reusing variables on a programming language.

**Comment by nathanpeck** [comment]
Great question. If you look at that `cdk.json` file you'll see this line:

https://github.com/aws-samples/aws-cdk-changelogs-demo/blob/master/cdk.json#L2

This defines what file to run when generating the app using CDK, in this case the `changelogs-md.js` file here: https://github.com/aws-samples/aws-cdk-changelogs-demo/blob/master/changelogs-md.js

You'll find the definitions for all the application resources right in there!

**Comment by Doug-AWS** [comment]
There are two main entry points to the CDK:

- The GitHub repo: https://github.com/awslabs/aws-cdk/README.md
- The guide: https://docs.aws.amazon.com/CDK/latest/userguide

**Comment by deleugpn** [comment]
The https://github.com/aws-samples/aws-cdk-changelogs-demo/blob/master/changelogs-md.js was exactly what I was looking. Thanks!
